apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sensor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sensor-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
