apiVersion: v1
kind: Service
metadata:
  name: sensor-service
  labels:
    app: sensor-service
spec:
  selector:
    app: sensor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
